spring:
  application:
    name: service-products
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring-boot

config:
  uploads:
    path: /tmp/

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
